ALTER TABLE applications
ADD COLUMN IF NOT EXISTS birth_date TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS nationality TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS current_country TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS education_level TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS program_type TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS program_duration TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS start_date TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS notes TEXT; 