INSERT INTO applications (
  first_name,
  last_name,
  email,
  phone,
  birth_date,
  nationality,
  current_country,
  education_level,
  english_level,
  french_level,
  program_type,
  program_duration,
  start_date,
  budget,
  notes,
  status
) VALUES (
  'Test',
  'User',
  'test@example.com',
  '+905551234567',
  '1990-01-01',
  'Turkish',
  'Turkey',
  'Bachelor',
  'Advanced',
  'Beginner',
  'Language Course',
  '6 months',
  '2024-09-01',
  '10000',
  'Test application',
  'pending'
); 